[
    {
       "title":"Oppenheimer",
       "video":"/videos/oppenheimer-trailer.mp4"
    },
    {
       "title":"Barbie",
       "video":"/videos/barbie-trailer.mp4"
    },
    {
       "title":"Interestelar",
       "video":"/videos/interstellar-trailer.mp4"
    }
 ]